{% set version = "0.12.0" %}

package:
  name: tmtoolkit
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tmtoolkit/tmtoolkit-{{ version }}.tar.gz
  sha256: 6df5429cd675989f21d9f075ddb11fe5ae273d6544fc337a2589bab2bc331909

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bidict
    - globre
    - matplotlib-base
    - numpy <2.0
    - openpyxl
    - pandas
    - python >={{ python_min }}
    - scipy
    - wheel
    - xlrd

test:
  imports:
    - tmtoolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/internaut/tmtoolkit
  summary: Text Mining and Topic Modeling Toolkit
  dev_url: https://github.com/internaut/tmtoolkit
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
